# Generated by Django 3.2 on 2021-04-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_answer_question'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answer',
            table='answer',
        ),
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
    ]
